### ISSUE TITLE
能不能增加支持子视图为Fragment？

### ISSUE THREAD

**Issue by zhongzilu** [xiepeijie/SwipeAdapterView#1]
现在的做法是，直接传数据集到Adapter，然后显示，能不能增加支持子视图为Fragment，这样数据就可以直接在Fragment里进行加载了

**Comment by ghost** [comment]
为什么导入我的工程 不能用 提示缺少R文件？请问怎么做？

**Comment by xiepeijie** [comment]
@SickoOrange 重新导一下R类呗
